name 'cookbook'
maintainer 'Chintan Shah'
maintainer_email 'mail@chintansh.com'
license 'all_rights'
description 'Installs/Configures cookbook'
long_description 'Installs/Configures cookbook'
version '0.1.0'
